version: '3'

services:
  support-bot:
    container_name: support-bot
    build:
      context: ../
      dockerfile: ./build/Dockerfile

  postgres:
    image: postgres:15-alpine
    container_name: postgres
