version: '3'

services:
  support-bot:
    container_name: support-bot
    build:
      context: ../
      dockerfile: ./build/Dockerfile

    volumes:
      - ../images/:/images/
      - ../web/:/web/

    ports:
      - "8080:8080"

    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=root
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d root" ]
      interval: 5s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root

